# SPDX-FileCopyrightText: © 2024 The "Toto" contributors <romain.brault@romainbrault.com>
#
# SPDX-License-Identifier: MIT

# Ignore everything.
**

# Except the following.

## Sources
!src/
!.git/
!pyproject.toml
!hatch.toml
!hatch_build.py
!LICENSES
!README.md
!uv.lock

## Template
!template
!jinja_template
!copier.yml
