# SPDX-FileCopyrightText: © 2024 The "Toto" contributors <romain.brault@romainbrault.com>
#
# SPDX-License-Identifier: MIT

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0
        flags:
          - unit
        paths:
          - "src"
          - "tests"
