# SPDX-FileCopyrightText: © 2024 The "Toto" contributors <romain.brault@romainbrault.com>
#
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "toto"
SPDX-PackageSupplier = "RomainBrault <>"
